// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TB.Infrastructure.Persistence;

#nullable disable

namespace TB.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009170011_SeedApplications")]
    partial class SeedApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TB.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobId", "CandidateId")
                        .IsUnique();

                    b.ToTable("applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            AppliedAtUtc = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CandidateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            JobId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Status = "Received"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            AppliedAtUtc = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CandidateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            JobId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Status = "Shortlisted"
                        });
                });

            modelBuilder.Entity("TB.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("candidate_skills", (string)null);

                    b.HasData(
                        new
                        {
                            CandidateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CandidateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            CandidateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            CandidateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            CandidateId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("TB.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("jobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build and improve hiring workflows across our .NET and Angular products.",
                            EmployerId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Location = "Addis Ababa (Hybrid)",
                            Title = "Full-Stack .NET Developer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design reliable APIs and data services for a growing recruitment platform.",
                            EmployerId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Location = "Remote",
                            Title = "Backend Engineer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create clear, accessible experiences for candidates and employers.",
                            EmployerId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Location = "Addis Ababa",
                            Title = "Angular Frontend Developer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Improve deployment automation, observability, and reliability for our cloud services.",
                            EmployerId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Location = "Remote",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build dependable data pipelines and PostgreSQL-backed services for our hiring platform.",
                            EmployerId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Location = "Addis Ababa (Hybrid)",
                            Title = "Data Engineer"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Design and maintain secure REST APIs that power our candidate and employer experiences.",
                            EmployerId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Location = "Remote",
                            Title = "API Developer"
                        });
                });

            modelBuilder.Entity("TB.Domain.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("job_skills", (string)null);

                    b.HasData(
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000001"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000001"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000001"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000001"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000006"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000007"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000003"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000003"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000005"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000003"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000006"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000007"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000004"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000008"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000005"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000007"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000006"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000006"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000006"),
                            IsRequired = true
                        },
                        new
                        {
                            JobId = new Guid("30000000-0000-0000-0000-000000000006"),
                            SkillId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsRequired = true
                        });
                });

            modelBuilder.Entity("TB.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Name = "REST APIs"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Name = "Docker"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Name = "Git"
                        });
                });

            modelBuilder.Entity("TB.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CompanyName = "Northstar Labs",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "employer@skillbridge.demo",
                            FullName = "Alex Morgan",
                            Location = "Addis Ababa",
                            PasswordHash = "$2a$12$RbeGHvbfZA0bETn2OUbutue9R3Wt.WjtCmroac.e4Lajmrh7RRTX6",
                            Role = "Employer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "candidate@skillbridge.demo",
                            FullName = "Sam Taylor",
                            Location = "Addis Ababa",
                            PasswordHash = "$2a$12$RbeGHvbfZA0bETn2OUbutue9R3Wt.WjtCmroac.e4Lajmrh7RRTX6",
                            Role = "Candidate"
                        });
                });

            modelBuilder.Entity("TB.Domain.Entities.Application", b =>
                {
                    b.HasOne("TB.Domain.Entities.User", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TB.Domain.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TB.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("TB.Domain.Entities.User", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TB.Domain.Entities.Skill", "Skill")
                        .WithMany("Candidates")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("TB.Domain.Entities.Job", b =>
                {
                    b.HasOne("TB.Domain.Entities.User", "Employer")
                        .WithMany("PostedJobs")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("TB.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("TB.Domain.Entities.Job", "Job")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TB.Domain.Entities.Skill", "Skill")
                        .WithMany("Jobs")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("TB.Domain.Entities.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("TB.Domain.Entities.Skill", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("TB.Domain.Entities.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CandidateSkills");

                    b.Navigation("PostedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
